// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbikqglekastbsyqcarn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaWtxZ2xla2FzdGJzeXFjYXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDMwMDIsImV4cCI6MjA2MzU3OTAwMn0.B3t7p5c9Q0v_uqIfA8UxLsI3dW33dI4XEVjj2--XqCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);